---
- name: "Debug"
  hosts: "all"
  tasks:
  - name: Dump all vars
    action: template src=templates/dumpall.j2 dest=/tmp/ansible.all
    # https://coderwall.com/p/13lh6w/dump-all-variables

- name: "Prepare to block outbound traffic on web"
  hosts: "web"
  tasks:
    - name: "Configure direct rules"
      copy:
        content: |
          <?xml version="1.0" encoding="utf-8"?>
          <direct>
            <rule priority="0" table="filter" ipv="ipv4" chain="OUTPUT">-p tcp -m tcp --dport=80 -j REJECT</rule>
            <rule priority="1" table="filter" ipv="ipv4" chain="OUTPUT">-p tcp -m tcp --dport=443 -j REJECT</rule>
          </direct>
        dest: "/etc/firewalld/direct.xml"
        mode: "0644"

- name: "Temporarily allow outbound traffic on web"
  hosts: "web"
  tasks:
    - name: "Stop firewalld"
      service:
        name: "firewalld"
        state: "stopped"

- name: "Configure mdns"
  hosts: "all"
  tasks:
    - name: "Install mdns packages"
      package:
        name: "{{ item }}"
        state: "present"
      with_items:
        - "avahi"
        - "avahi-tools"
        - "nss-mdns"
    - name: "Start avahi daemon"
      service:
        name: "avahi-daemon"
        enabled: "yes"
        state: "started"

- name: "Add PHP"
  hosts: "all"
  tasks:
    - name: "Install SCL repo"
      package:
        name: "{{ item }}"
        state: "present"
      with_items:
        - "centos-release-scl"
    - name: "Install PHP CLI"
      package:
        name: "{{ item }}"
        state: "present"
      with_items:
        - "rh-php71-php-cli"

- name: "Block outbound traffic on web"
  hosts: "web"
  tasks:
    - name: "Start firewalld"
      service:
        name: "firewalld"
        state: "started"
