---
- name: "Debug"
  hosts: "all"
  tasks:
  - name: Dump all vars
    action: template src=templates/dumpall.j2 dest=/tmp/ansible.all
    # https://coderwall.com/p/13lh6w/dump-all-variables

- name: "Configure mdns"
  hosts: "all"
  tasks:
    - name: "Install mdns packages"
      package:
        name: "{{ item }}"
        state: "present"
      with_items:
        - "avahi"
        - "avahi-tools"
        - "nss-mdns"
    - name: "Start avahi daemon"
      service:
        name: "avahi-daemon"
        enabled: "yes"
        state: "started"
