---
- name: "Debug"
  hosts: "all"
  tasks:
    - name: "Dump vars"
      copy:
        content: |
          {{ vars | to_nice_json }}
        dest: "/tmp/ansible.vars.json"
    - name: "Dump environment"
      copy:
        content: |
          {{ environment | to_nice_json }}
        dest: "/tmp/ansible.environment.json"
    - name: "Dump group_names"
      copy:
        content: |
          {{ group_names | to_nice_json }}
        dest: "/tmp/ansible.group_names.json"
    - name: "Dump groups"
      copy:
        content: |
          {{ groups | to_nice_json }}
        dest: "/tmp/ansible.groups.json"
    - name: "Dump hostvars"
      copy:
        content: |
          {{ hostvars | to_nice_json }}
        dest: "/tmp/ansible.hostvars.json"

- name: "Prepare to block outbound traffic"
  hosts: "all"
  tasks:
    - name: "Configure direct rules"
      copy:
        content: |
          <?xml version="1.0" encoding="utf-8"?>
          <direct>
            <rule priority="0" table="filter" ipv="ipv4" chain="OUTPUT">-m state --state INVALID -j DROP</rule>
            <rule priority="1" table="filter" ipv="ipv4" chain="OUTPUT">-m state --state RELATED,ESTABLISHED -j ACCEPT</rule>
            <rule priority="2" table="filter" ipv="ipv4" chain="OUTPUT">-d {{ ansible_default_ipv4.gateway }} -j ACCEPT</rule>
            <rule priority="3" table="filter" ipv="ipv4" chain="OUTPUT">-d {{ ansible_dns.nameservers[0] }} -j ACCEPT</rule>
            <rule priority="4" table="filter" ipv="ipv4" chain="OUTPUT">-j REJECT</rule>
          </direct>
        dest: "/etc/firewalld/direct.xml"
        mode: "0644"

- name: "Temporarily allow outbound traffic"
  hosts: "all"
  tasks:
    - name: "Stop firewalld"
      service:
        name: "firewalld"
        state: "stopped"

- name: "Add PHP"
  hosts: "all"
  tasks:
    - name: "Install SCL repo"
      package:
        name: "{{ item }}"
        state: "present"
      with_items:
        - "centos-release-scl"
    - name: "Install PHP CLI"
      package:
        name: "{{ item }}"
        state: "present"
      with_items:
        - "rh-php71-php-cli"

- name: "Add composer"
  hosts: "all"
  tasks:
    - name: "Download composer phar"
      get_url:
        url: "https://github.com/composer/composer/releases/download/1.6.3/composer.phar"
        checksum: "sha256:52cb7bbbaee720471e3b34c8ae6db53a38f0b759c06078a80080db739e4dcab6"
        dest: "/usr/local/bin/composer.phar"
        mode: "0755"
    - name: "Create composer wrapper for SCL PHP"
      copy:
        content: |
          #!/usr/bin/bash
          scl enable rh-php71 -- /usr/local/bin/composer.phar "$@"
        dest: "/usr/local/bin/composer"
        mode: "0755"

- name: "Block outbound traffic"
  hosts: "all"
  tasks:
    - name: "Start firewalld"
      service:
        name: "firewalld"
        state: "started"
